<a href="https://colab.research.google.com/github/Abrar-404/AI-ML_Practices_and_Assignments/blob/main/Module_07_re_practice(Again_did_practice).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Mandatory Problems

# 1. Diabetes Dataset – Missing Value Imputation & Encoding

Dataset Link:
Pima Indians Diabetes Dataset

Use the Pima Indians Diabetes Database dataset.

Tasks:
- Load the dataset using Pandas.
- Check missing values using isnull().sum().
- Replace invalid 0 values in columns like Glucose, BloodPressure, and BMI with NaN.

Apply:
- Necessary Imputation ( Must be done with the proper one )
- Create a categorical column:
- Age_Group (Young (<30), Adult (30–50), Senior (>50))
- Apply Encoding on Age_Group.

Choose the proper encoding technique and explain why it is the best one.

In [24]:
# Load the dataset using Pandas.
diabetes = pd.read_csv('diabetes.csv')

# Check missing values using isnull().sum().
diabetes.isnull().sum()

# Replace invalid 0 values in columns like Glucose, BloodPressure, and BMI with NaN.
diabetes[['Glucose', 'BloodPressure', 'BMI']] = diabetes[['Glucose', 'BloodPressure', 'BMI']].replace(0, np.nan)

# Necessary Imputation ( Must be done with the proper one )
diabetes_median = diabetes[['Glucose', 'BloodPressure', 'BMI']].median()
diabetes[['Glucose', 'BloodPressure', 'BMI']] = diabetes[['Glucose', 'BloodPressure', 'BMI']].fillna(diabetes_median)

# Create a categorical column: Age_Group (Young (<30), Adult (30–50), Senior (>50))
diabetes['Age_Group'] = pd.cut(diabetes['Age'], bins = [0, 29, 50, 100], labels = ['Young', 'Adult', 'Senior'], right = True)

# Apply Encoding on Age_Group.
age_ord = OrdinalEncoder(categories=[['Young', 'Adult', 'Senior']])

age_ord.fit(diabetes[['Age_Group']])
diabetes['Age_Encoded'] = age_ord.transform(diabetes[['Age_Group']]).ravel()
diabetes

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Age_Group,Age_Encoded
0,6,148.0,72.0,35,0,33.6,0.627,50,1,Adult,1.0
1,1,85.0,66.0,29,0,26.6,0.351,31,0,Adult,1.0
2,8,183.0,64.0,0,0,23.3,0.672,32,1,Adult,1.0
3,1,89.0,66.0,23,94,28.1,0.167,21,0,Young,0.0
4,0,137.0,40.0,35,168,43.1,2.288,33,1,Adult,1.0
...,...,...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48,180,32.9,0.171,63,0,Senior,2.0
764,2,122.0,70.0,27,0,36.8,0.340,27,0,Young,0.0
765,5,121.0,72.0,23,112,26.2,0.245,30,0,Adult,1.0
766,1,126.0,60.0,0,0,30.1,0.349,47,1,Adult,1.0
767,1,93.0,70.0,31,0,30.4,0.315,23,0,Young,0.0

# 2. Heart Disease Dataset – One Hot Encoding

Dataset Link:
Heart Disease UCI Dataset

Use the Heart Disease UCI Dataset dataset.

Tasks:
- Load the dataset.
- Identify categorical columns.
- Apply  Encoding on: cp (chest pain type),
thal
- Compare dataframe shape before and after encoding.

In [25]:
# Load the dataset.
heart = pd.read_csv('heart.csv')
print('Shape Before:', heart.shape)

# Identify categorical columns.
cat_col = heart.select_dtypes(include='object').columns
# Ans: Sex, CP, fbs, restecg, exang, slope, ca, thal, target

# Apply Encoding on: cp (chest pain type), thal
# for cp
cp_ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore').set_output(transform = 'pandas')
cp_ohe.fit(heart[['cp']])
cp_encoded = cp_ohe.transform(heart[['cp']])
heart = pd.concat([heart, cp_encoded], axis = 1)

# for thal
thal_ohe = OneHotEncoder(sparse_output = False, handle_unknown='ignore').set_output(transform = 'pandas')
thal_ohe.fit(heart[['thal']])
thal_encoded = thal_ohe.transform(heart[['thal']])
heart = pd.concat([heart, thal_encoded], axis = 1)

heart = heart.drop(columns=['cp', 'thal'])
# Compare dataframe shape before and after encoding.
print('Shape After:', heart.shape)
#Ans: Before encoding the dataframe included no specific column for each types of Cp and thal but after encoding it includes specific columns for cp and thal types.

Shape Before: (1025, 14)
Shape After: (1025, 20)

# 3. Tips Dataset – Label Encoding

Dataset Link:
Seaborn Tips Dataset

Use the Tips Dataset dataset.

Tasks:
- Load dataset using Seaborn.
- Apply  Encoding on: sex, smoker
- Create a new feature: tip_category (Low (<3), Medium (3–6), High (>6))
- Encode tip_category.

Choose the proper encoding technique and explain why it is the best one.

In [26]:
# Load dataset using Seaborn.
tips = sns.load_dataset('tips')

# Apply Encoding on: sex, smoker

# for sex
le_sex = LabelEncoder()
le_sex.fit(tips['sex'])
le_sex_array = le_sex.transform(tips['sex'])
sex_encoded = pd.Series(le_sex_array, index = tips['sex'].index, name = tips['sex'].name)

# for smoker
le_smoker = LabelEncoder()
le_smoker.fit(tips['smoker'])
le_smoker_array = le_smoker.transform(tips['smoker'])
smoker_encoded = pd.Series(le_smoker_array, index = tips['smoker'].index, name = tips['smoker'].name)

# drop the main columns
tips = tips.drop(columns = ['sex', 'smoker'], axis = 1)
tips['sex'] = sex_encoded
tips['smoker'] = smoker_encoded

# Create a new feature: tip_category (Low (<3), Medium (3–6), High (>6))
tips['tip_category'] = pd.cut(tips['tip'], bins = [0, 2, 6, 100], labels = ['Low', 'Medium', 'High'], right = True)

# Encode tip_category.
tip_encoded = OrdinalEncoder(categories=[['Low', 'Medium', 'High']])
tip_encoded.fit(tips[['tip_category']])
tips['tip_encoded'] = tip_encoded.transform(tips[['tip_category']]).ravel()

# Choose the proper encoding technique and explain why it is the best one.
# LabelEncoder for sex & smoker — binary columns (2 categories), 0/1 is sufficient.
# OrdinalEncoder for tip_category — natural order: Low < Medium < High.

tips

,total_bill,tip,day,time,size,sex,smoker,tip_category,tip_encoded
0,16.99,1.01,Sun,Dinner,2,0,0,Low,0.0
1,10.34,1.66,Sun,Dinner,3,1,0,Low,0.0
2,21.01,3.50,Sun,Dinner,3,1,0,Medium,1.0
3,23.68,3.31,Sun,Dinner,2,1,0,Medium,1.0
4,24.59,3.61,Sun,Dinner,4,0,0,Medium,1.0
...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Sat,Dinner,3,1,0,Medium,1.0
240,27.18,2.00,Sat,Dinner,2,0,1,Low,0.0
241,22.67,2.00,Sat,Dinner,2,1,1,Low,0.0
242,17.82,1.75,Sat,Dinner,2,1,0,Low,0.0
243,18.78,3.00,Thur,Dinner,2,0,0,Medium,1.0

# 4. Car Price Dataset – Train/Test Encoding Pipeline

Dataset Link:
Car Price Prediction Dataset

Use the Car Price Prediction Dataset dataset.

Tasks:
- Split the dataset into train and test sets first.
- Apply: Ordinal Encoding on fuel type (Petrol, Diesel, CNG), One Hot Encoding on transmission type
- Handle unknown categories in test data properly.
- Concatenate encoded columns with original dataframe.
- Drop original categorical columns.

In [27]:
cars = pd.read_csv('CarPrice_Assignment.csv')

# Split the dataset into train and test sets first.
X = cars.drop('price', axis = 1)
y = cars['price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Apply: Ordinal Encoding on fuel type (Petrol, Diesel, CNG), Handle unknown categories in test data properly.
fuel_ord = OrdinalEncoder(categories = [['gas', 'diesel']])
fuel_ord.fit(X_train[['fueltype']])
X_train['fuel_encoded'] = fuel_ord.transform(X_train[['fueltype']]).ravel()
X_test['fuel_encoded'] = fuel_ord.transform(X_test[['fueltype']]).ravel()

# Apply: One Hot Encoding on transmission type, Handle unknown categories in test data properly.
tran_ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore').set_output(transform = 'pandas')
tran_ohe.fit(X_train[['drivewheel']])
tran_train_encoded = tran_ohe.transform(X_train[['drivewheel']])
tran_test_encoded = tran_ohe.transform(X_test[['drivewheel']])

# Concatenate encoded columns with original dataframe.
X_train = pd.concat([X_train, tran_train_encoded], axis = 1)
X_test = pd.concat([X_test, tran_test_encoded], axis = 1)

# Drop original categorical columns.
X_train = X_train.drop(columns = ['fueltype', 'drivewheel'])
X_test = X_test.drop(columns = ['fueltype', 'drivewheel'])

# Optional Problems

# 5. Heart Disease Dataset – Full Preprocessing Pipeline
Dataset Link:
Heart Disease UCI Dataset

Use the Heart Disease UCI Dataset dataset.

Tasks:

Build a preprocessing pipeline that includes:
- Missing value imputation
- Outlier detection using IQR
- One Hot Encoding
- Ordinal Encoding
- Use ColumnTransformer and Pipeline.
- Transform both training and testing datasets properly.
- Display final transformed feature matrix shape.

In [28]:
heart_df = pd.read_csv('heart.csv')

# split first
X = heart_df.drop('target', axis = 1)
y = heart_df['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Missing value imputation
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(X_train)
X_train = pd.DataFrame(imputer.transform(X_train), columns = X_train.columns)
X_test = pd.DataFrame(imputer.transform(X_test), columns = X_test.columns)

# Outlier detection using IQR
numeric_cols = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']

for cols in numeric_cols:
  Q1 = X_train[cols].quantile(0.25)
  Q3 = X_train[cols].quantile(0.75)

  IQR = Q3 - Q1

  lower_bound = Q1 - 1.5 * IQR
  upper_bound = Q3 + 1.5 * IQR

  X_train = X_train[(X_train[cols] >= lower_bound) & (X_train[cols] <= upper_bound)]

print('Shape after IQR removal:', X_train.shape)


# Use ColumnTransformer and Pipeline.

# One Hot Encoding
cp_ohe = Pipeline([('ohe', OneHotEncoder(sparse_output = False, handle_unknown = 'ignore').set_output(transform = 'pandas'))])

# ordinal encoding
thal_ord = Pipeline([('ord', OrdinalEncoder(categories = [[0, 1, 2, 3]], handle_unknown='use_encoded_value', unknown_value = np.nan))])

# ColumnTransformer combining both
preprocessor = ColumnTransformer(transformers = [('cp_ohe', cp_ohe, ['cp']), ('thal_ord', thal_ord, ['thal'])], remainder = 'passthrough')

# Transform both training and testing datasets properly.
X_train_transformed = preprocessor.fit_transform(X_train)
X_test_transformed = preprocessor.transform(X_test)

# Display final transformed feature matrix shape
print('X_train transformed shape:', X_train_transformed.shape)
print('X_test  transformed shape:', X_test_transformed.shape)

Shape after IQR removal: (774, 13)
X_train transformed shape: (774, 16)
X_test  transformed shape: (205, 16)

# 6. Diabetes Dataset – Compare Encoding Techniques
Dataset Link:
Pima Indians Diabetes Dataset

Use the Pima Indians Diabetes Database dataset.

Tasks:

Create a categorical feature from BMI:
- Underweight
- Normal
- Overweight
- Obese

Apply:
- Label Encoding
- Ordinal Encoding
- One Hot Encoding

Write a short conclusion on which encoding is best for this feature.

In [33]:
diab = pd.read_csv('diabetes.csv')

# Create a categorical feature from BMI: 1. Underweight 2.Normal 3.Overweight 4.Obese
diab['BMI_Status'] = pd.cut(diab['BMI'], bins = [0, 18.5, 24.9, 29.9, 100], labels = ['Underweight', 'Normal', 'Overweight', 'Obese'])

# Label Encoding
le = LabelEncoder()
le.fit(diab['BMI_Status'])
diab['BMI_Encoded'] = le.transform(diab['BMI_Status'])
diab_outcome = pd.Series(diab['BMI_Encoded'], index = diab['BMI_Status'].index, name = diab['BMI_Status'].name)

# Ordinal Encoding
diab_ord = OrdinalEncoder(categories = [['Underweight', 'Normal', 'Overweight', 'Obese']], handle_unknown = 'use_encoded_value', unknown_value = np.nan)
diab_ord.fit(diab[['BMI_Status']])
diab['BMI_Encoded'] = diab_ord.transform(diab[['BMI_Status']]).ravel()

# One Hot Encoding
diab_ohe = OneHotEncoder(sparse_output = False, handle_unknown = 'ignore').set_output(transform = 'pandas')
diab_ohe.fit(diab[['BMI_Status']])
diab_encoded = diab_ohe.transform(diab[['BMI_Status']])
diab = pd.concat([diab, diab_encoded], axis = 1)

# Write a short conclusion on which encoding is best for this feature.
# Ordinal Encoding is the best for BMI_State because the categories have a clear natural order: Underweight < Normal < Overweight < Obese.
# Label Encoding also preserves order but assigns arbitrary integers without guaranteeing the correct sequence.
# One Hot Encoding is the worst choice here because it ignores the natural order and adds 4 extra columns unnecessarily.

# 7. Hotel Booking Dataset – High Cardinality Encoding
Dataset Link:
Hotel Booking Demand Dataset

Use the Hotel Booking Demand Dataset dataset.

Tasks:
- Load dataset.
- Identify high-cardinality categorical columns.

Apply:
- One Hot Encoding on hotel
- Label Encoding on booking status column

In [39]:
# Load dataset.
hotel = pd.read_csv('hotel_bookings.csv')

# Identify high-cardinality categorical columns.
cat_cols = hotel.select_dtypes(include = 'object').columns
print('high-cardinality categorical columns: \n', hotel[cat_cols].nunique().sort_values(ascending=False))

# One Hot Encoding on hotel
hotel_ohe = OneHotEncoder(sparse_output = False, handle_unknown = 'ignore').set_output(transform = 'pandas')
hotel_ohe.fit(hotel[['hotel']])
hotel_encoded = hotel_ohe.transform(hotel[['hotel']])
hotel = pd.concat([hotel, hotel_encoded], axis = 1)

# Label Encoding on booking status column
le = LabelEncoder()
le.fit(hotel['reservation_status'])
hotel['reserve_encoded'] = le.transform(hotel['reservation_status'])
hotel_outcome = pd.Series(hotel['reserve_encoded'], index = hotel['reservation_status'].index, name = hotel['reservation_status'].name)

hotel = hotel.drop('hotel', axis = 1)
hotel

high-cardinality categorical columns:
 reservation_status_date    926
country                    177
assigned_room_type          12
arrival_date_month          12
reserved_room_type          10
market_segment               8
distribution_channel         5
meal                         5
customer_type                4
deposit_type                 3
reservation_status           3
hotel                        2
dtype: int64

,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,hotel_City Hotel,hotel_Resort Hotel,reserve_encoded
0,0,342,2015,July,27,1,0,0,2,0.0,...,0,Transient,0.00,0,0,Check-Out,2015-07-01,0.0,1.0,1
1,0,737,2015,July,27,1,0,0,2,0.0,...,0,Transient,0.00,0,0,Check-Out,2015-07-01,0.0,1.0,1
2,0,7,2015,July,27,1,0,1,1,0.0,...,0,Transient,75.00,0,0,Check-Out,2015-07-02,0.0,1.0,1
3,0,13,2015,July,27,1,0,1,1,0.0,...,0,Transient,75.00,0,0,Check-Out,2015-07-02,0.0,1.0,1
4,0,14,2015,July,27,1,0,2,2,0.0,...,0,Transient,98.00,0,1,Check-Out,2015-07-03,0.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,0,23,2017,August,35,30,2,5,2,0.0,...,0,Transient,96.14,0,0,Check-Out,2017-09-06,1.0,0.0,1
119386,0,102,2017,August,35,31,2,5,3,0.0,...,0,Transient,225.43,0,2,Check-Out,2017-09-07,1.0,0.0,1
119387,0,34,2017,August,35,31,2,5,2,0.0,...,0,Transient,157.71,0,4,Check-Out,2017-09-07,1.0,0.0,1
119388,0,109,2017,August,35,31,2,5,2,0.0,...,0,Transient,104.40,0,0,Check-Out,2017-09-07,1.0,0.0,1
119389,0,205,2017,August,35,29,2,7,2,0.0,...,0,Transient,151.20,0,2,Check-Out,2017-09-07,1.0,0.0,1

# 8. Employee Attrition Dataset – Advanced Encoding Challenge
Dataset Link:
IBM HR Analytics Employee Attrition Dataset

Use the IBM HR Analytics Employee Attrition Dataset dataset.

Tasks:
- Split the dataset into train and test sets.
- Detects all categorical columns automatically.

Apply:
- Ordinal Encoding for education level
- One Hot Encoding for department
- Label Encoding for target column
- Handle unseen categories in test data.
- Create a reusable preprocessing function.
- Display transformed train and test datasets.

In [48]:
hr = pd.read_csv('HR_Analytics.csv')

# Split the dataset into train and test sets.
X = hr.drop('Attrition', axis = 1)
y = hr['Attrition']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Detects all categorical columns automatically.
hr_cols = hr.select_dtypes(include = 'object').columns

# Ordinal Encoding for education level, Handle unseen categories in test data.
X_train['Education_level'] = pd.cut(X_train['Education'], bins = [0, 1, 2, 3, 4, 5], labels = ['SSC', 'HSC', 'BBA', 'MBA', 'PHD'])
X_test['Education_level'] = pd.cut(X_test['Education'], bins = [0, 1, 2, 3, 4, 5], labels = ['SSC', 'HSC', 'BBA', 'MBA', 'PHD'])

Edu_Encoded = OrdinalEncoder(categories = [['SSC', 'HSC', 'BBA', 'MBA', 'PHD']], handle_unknown = 'use_encoded_value', unknown_value = np.nan)
Edu_Encoded.fit(X_train[['Education_level']])
X_train['Education_Encoded'] = Edu_Encoded.transform(X_train[['Education_level']])
X_test['Education_Encoded'] = Edu_Encoded.transform(X_test[['Education_level']])

# Label Encoding for target column
le = LabelEncoder()
le.fit(y_train)
y_train_array = le.transform(y_train)
y_test_array = le.transform(y_test)

y_train_encoded = pd.Series(y_train_array, index = y_train.index, name = y_train.name)
y_test_encoded = pd.Series(y_test_array, index = y_test.index, name = y_test.name)

# One Hot Encoding for department
dept_ohe = OneHotEncoder(sparse_output = False, handle_unknown = 'ignore').set_output(transform = 'pandas')
dept_ohe.fit(X_train[['Department']])
dept_train_encoded = dept_ohe.transform(X_train[['Department']])
dept_test_encoded = dept_ohe.transform(X_test[['Department']])

X_train = pd.concat([X_train, dept_train_encoded], axis = 1)
X_test = pd.concat([X_test, dept_test_encoded], axis = 1)

# Create a reusable preprocessing function.
def preprocessor(X_train, X_test, y_train, y_test):
  # Ordinal Encoding for education level, Handle unseen categories in test data.
  X_train['Education_level'] = pd.cut(X_train['Education'], bins = [0, 1, 2, 3, 4, 5], labels = ['SSC', 'HSC', 'BBA', 'MBA', 'PHD'])
  X_test['Education_level'] = pd.cut(X_test['Education'], bins = [0, 1, 2, 3, 4, 5], labels = ['SSC', 'HSC', 'BBA', 'MBA', 'PHD'])

  Edu_Encoded = OrdinalEncoder(categories = [['SSC', 'HSC', 'BBA', 'MBA', 'PHD']], handle_unknown = 'use_encoded_value', unknown_value = np.nan)
  Edu_Encoded.fit(X_train[['Education_level']])
  X_train['Education_Encoded'] = Edu_Encoded.transform(X_train[['Education_level']])
  X_test['Education_Encoded'] = Edu_Encoded.transform(X_test[['Education_level']])

  # Label Encoding for target column
  le = LabelEncoder()
  le.fit(y_train)
  y_train_array = le.transform(y_train)
  y_test_array = le.transform(y_test)

  y_train_encoded = pd.Series(y_train_array, index = y_train.index, name = y_train.name)
  y_test_encoded = pd.Series(y_test_array, index = y_test.index, name = y_test.name)

  # One Hot Encoding for department
  dept_ohe = OneHotEncoder(sparse_output = False, handle_unknown = 'ignore').set_output(transform = 'pandas')
  dept_ohe.fit(X_train[['Department']])
  dept_train_encoded = dept_ohe.transform(X_train[['Department']])
  dept_test_encoded = dept_ohe.transform(X_test[['Department']])

  X_train = pd.concat([X_train, dept_train_encoded], axis = 1)
  X_test = pd.concat([X_test, dept_test_encoded], axis = 1)

  return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = preprocessor(X_train, X_test, y_train, y_test)

# Display transformed train and test datasets
print('X_train shape:', X_train.shape)
print('X_test  shape:', X_test.shape)
X_train

X_train shape: (1176, 42)
X_test  shape: (294, 42)

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,YearsSinceLastPromotion,YearsWithCurrManager,Education_level,Education_Encoded,Department_Human Resources,Department_Research & Development,Department_Sales,Department_Human Resources,Department_Research & Development,Department_Sales
1097,24,Travel_Rarely,350,Research & Development,21,2,Technical Degree,1,1551,3,...,0,0,HSC,1.0,0.0,1.0,0.0,0.0,1.0,0.0
727,18,Non-Travel,287,Research & Development,5,2,Life Sciences,1,1012,2,...,0,0,HSC,1.0,0.0,1.0,0.0,0.0,1.0,0.0
254,29,Travel_Rarely,1247,Sales,20,2,Marketing,1,349,4,...,0,2,HSC,1.0,0.0,0.0,1.0,0.0,0.0,1.0
1175,39,Travel_Rarely,492,Research & Development,12,3,Medical,1,1654,4,...,1,0,BBA,2.0,0.0,1.0,0.0,0.0,1.0,0.0
1341,31,Travel_Rarely,311,Research & Development,20,3,Life Sciences,1,1881,2,...,0,2,BBA,2.0,0.0,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1130,35,Travel_Rarely,750,Research & Development,28,3,Life Sciences,1,1596,2,...,6,8,BBA,2.0,0.0,1.0,0.0,0.0,1.0,0.0
1294,41,Travel_Rarely,447,Research & Development,5,3,Life Sciences,1,1814,2,...,1,2,BBA,2.0,0.0,1.0,0.0,0.0,1.0,0.0
860,22,Travel_Frequently,1256,Research & Development,3,4,Life Sciences,1,1203,3,...,0,0,MBA,3.0,0.0,1.0,0.0,0.0,1.0,0.0
1459,29,Travel_Rarely,1378,Research & Development,13,2,Other,1,2053,4,...,0,3,HSC,1.0,0.0,1.0,0.0,0.0,1.0,0.0
1126,50,Travel_Rarely,264,Sales,9,3,Marketing,1,1591,3,...,0,0,BBA,2.0,0.0,0.0,1.0,0.0,0.0,1.0