<a href="https://colab.research.google.com/github/Abrar-404/AI-ML_Practices_and_Assignments/blob/main/Module_07_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [244]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Mandatory Problems

# 1. Diabetes Dataset – Missing Value Imputation & Encoding

Dataset Link:
Pima Indians Diabetes Dataset

Use the Pima Indians Diabetes Database dataset.

Tasks:
- Load the dataset using Pandas.
- Check missing values using isnull().sum().
- Replace invalid 0 values in columns like Glucose, BloodPressure, and BMI with NaN.

Apply:
- Necessary Imputation ( Must be done with the proper one )
- Create a categorical column:
- Age_Group (Young (<30), Adult (30–50), Senior (>50))
- Apply Encoding on Age_Group.

Choose the proper encoding technique and explain why it is the best one.

In [245]:
# Load the dataset using Pandas.
diabetes = pd.read_csv('diabetes.csv')

# Check missing values using isnull().sum().
diabetes.isnull().sum()

# Replace invalid 0 values in columns like Glucose, BloodPressure, and BMI with NaN.
diabetes[['Glucose', 'BloodPressure', 'BMI']] = diabetes[['Glucose', 'BloodPressure', 'BMI']].replace(0, np.nan)

# Necessary Imputation ( Must be done with the proper one )
diabetes_median = diabetes[['Glucose', 'BloodPressure', 'BMI']].median()
diabetes[['Glucose', 'BloodPressure', 'BMI']] = diabetes[['Glucose', 'BloodPressure', 'BMI']].fillna(diabetes_median)

# Create a categorical column: Age_Group (Young (<30), Adult (30–50), Senior (>50))
diabetes['Age_group'] = pd.cut(diabetes['Age'], bins = [-1, 29, 50, 100], labels = ['Young', 'Adult', 'Senior'], right=True)

# Apply Encoding on Age_Group
diabetes_encoder = OrdinalEncoder(categories=[['Young', 'Adult', 'Senior']])
diabetes_encoder.fit(diabetes[['Age_group']])

diabetes['Encoded_diabetes'] = diabetes_encoder.transform(diabetes[['Age_group']]).ravel()

diabetes

# Choose the proper encoding technique and explain why it is the best one.
# Ans: The ordinal encoding is the best one in this case because the age group includes three different categories of people and Ordinal Encoding is the best choice here because Age_Group has a NATURAL, MEANINGFUL ORDER: Young < Adult < Senior..

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Age_group,Encoded_diabetes
0,6,148.0,72.0,35,0,33.6,0.627,50,1,Adult,1.0
1,1,85.0,66.0,29,0,26.6,0.351,31,0,Adult,1.0
2,8,183.0,64.0,0,0,23.3,0.672,32,1,Adult,1.0
3,1,89.0,66.0,23,94,28.1,0.167,21,0,Young,0.0
4,0,137.0,40.0,35,168,43.1,2.288,33,1,Adult,1.0
...,...,...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48,180,32.9,0.171,63,0,Senior,2.0
764,2,122.0,70.0,27,0,36.8,0.340,27,0,Young,0.0
765,5,121.0,72.0,23,112,26.2,0.245,30,0,Adult,1.0
766,1,126.0,60.0,0,0,30.1,0.349,47,1,Adult,1.0
767,1,93.0,70.0,31,0,30.4,0.315,23,0,Young,0.0

# 2. Heart Disease Dataset – One Hot Encoding

Dataset Link:
Heart Disease UCI Dataset

Use the Heart Disease UCI Dataset dataset.

Tasks:
- Load the dataset.
- Identify categorical columns.
- Apply  Encoding on: cp (chest pain type),
thal
- Compare dataframe shape before and after encoding.

In [246]:
# Load the dataset.
heart_df = pd.read_csv('heart.csv')

print('Shape Before:', heart_df.shape)
# Identify categorical columns.
# Ans: Sex, CP, fbs, restecg, exang, slope, ca, thal, target

# Apply Encoding on: cp (chest pain type), thal

# CP
cp_ohe = OneHotEncoder(sparse_output=False).set_output(transform = 'pandas')

cp_ohe.fit(heart_df[['cp']])
cp_encoded = cp_ohe.transform(heart_df[['cp']])
heart_df = pd.concat([heart_df, cp_encoded], axis = 1)

# thal
thal_ohe = OneHotEncoder(sparse_output=False).set_output(transform = 'pandas')

thal_ohe.fit(heart_df[['thal']])
thal_encoded = thal_ohe.transform(heart_df[['thal']])
heart_df = pd.concat([heart_df, thal_encoded], axis = 1)


heart_df = heart_df.drop(columns=['cp', 'thal'])

# Compare dataframe shape before and after encoding.
print('Shape After:', heart_df.shape)
#Ans: Before encoding the dataframe included no specific column for each types of Cp and thal but after encoding it includes specific columns for cp and thal types.

heart_df

Shape Before: (1025, 14)
Shape After: (1025, 20)

,age,sex,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,target,cp_0,cp_1,cp_2,cp_3,thal_0,thal_1,thal_2,thal_3
0,52,1,125,212,0,1,168,0,1.0,2,2,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,53,1,140,203,1,0,155,1,3.1,0,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,70,1,145,174,0,1,125,1,2.6,0,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,61,1,148,203,0,1,161,0,0.0,2,1,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,62,0,138,294,1,1,106,0,1.9,1,3,0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,140,221,0,1,164,1,0.0,2,0,1,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1021,60,1,125,258,0,0,141,1,2.8,1,1,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1022,47,1,110,275,0,0,118,1,1.0,1,1,0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1023,50,0,110,254,0,0,159,0,0.0,2,0,1,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1024,54,1,120,188,0,1,113,0,1.4,1,1,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

# 3. Tips Dataset – Label Encoding

Dataset Link:
Seaborn Tips Dataset

Use the Tips Dataset dataset.

Tasks:
- Load dataset using Seaborn.
- Apply  Encoding on: sex, smoker
- Create a new feature: tip_category (Low (<3), Medium (3–6), High (>6))
- Encode tip_category.

Choose the proper encoding technique and explain why it is the best one.

In [247]:
# Load dataset using Seaborn.
tips_df = sns.load_dataset('tips')

# Apply Encoding on: sex, smoker

# sex
le_sex = LabelEncoder()

le_sex.fit(tips_df['sex'])
le_sex_array = le_sex.transform(tips_df['sex'])

sex_encoded = pd.Series(le_sex_array, index = tips_df['sex'].index, name =  tips_df['sex'].name)
tips_df['sex_encoded'] = le_sex.fit_transform(tips_df['sex'])

# smoker
le_smoker = LabelEncoder()

le_smoker.fit(tips_df['smoker'])
le_smoker_array = le_smoker.transform(tips_df['smoker'])

smoker_encoded = pd.Series(le_smoker_array, index = tips_df['smoker'].index, name =  tips_df['smoker'].name)
tips_df['smoker_encoded'] = le_smoker.transform(tips_df['smoker'])

# Create a new feature: tip_category (Low (<3), Medium (3–6), High (>6))
tips_df['tip_category'] = pd.cut(tips_df['tip'], bins = [0, 3, 6, 100], labels = ['Low', 'Medium', 'High'], right = True)

# Encode tip_category.
tip_cat_encoded = OrdinalEncoder(categories = [['Low', 'Medium', 'High']])

tip_cat_encoded.fit(tips_df[['tip_category']])
tips_df['tip_category_encoded'] = tip_cat_encoded.transform(tips_df[['tip_category']])

tips_df = tips_df.drop(columns = ['sex', 'smoker'])
tips_df

# Choose the proper encoding technique and explain why it is the best one.
# LabelEncoder for sex & smoker — binary columns (2 categories), 0/1 is sufficient.
# OrdinalEncoder for tip_category — natural order: Low < Medium < High.

,total_bill,tip,day,time,size,sex_encoded,smoker_encoded,tip_category,tip_category_encoded
0,16.99,1.01,Sun,Dinner,2,0,0,Low,0.0
1,10.34,1.66,Sun,Dinner,3,1,0,Low,0.0
2,21.01,3.50,Sun,Dinner,3,1,0,Medium,1.0
3,23.68,3.31,Sun,Dinner,2,1,0,Medium,1.0
4,24.59,3.61,Sun,Dinner,4,0,0,Medium,1.0
...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Sat,Dinner,3,1,0,Medium,1.0
240,27.18,2.00,Sat,Dinner,2,0,1,Low,0.0
241,22.67,2.00,Sat,Dinner,2,1,1,Low,0.0
242,17.82,1.75,Sat,Dinner,2,1,0,Low,0.0
243,18.78,3.00,Thur,Dinner,2,0,0,Low,0.0

# 4. Car Price Dataset – Train/Test Encoding Pipeline

Dataset Link:
Car Price Prediction Dataset

Use the Car Price Prediction Dataset dataset.

Tasks:
- Split the dataset into train and test sets first.
- Apply: Ordinal Encoding on fuel type (Petrol, Diesel, CNG), One Hot Encoding on transmission type
- Handle unknown categories in test data properly.
- Concatenate encoded columns with original dataframe.
- Drop original categorical columns.

In [248]:
car_df = pd.read_csv('CarPrice_Assignment.csv')
car_df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [249]:
# Split the dataset into train and test sets first.
X = car_df.drop(['price'], axis = 1)
y = car_df['price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Apply: Ordinal Encoding on fuel type (Petrol, Diesel, CNG)
fuel_encoded = OrdinalEncoder(categories = [['Petrol', 'Diesel', 'CNG']], handle_unknown = 'use_encoded_value', unknown_value = np.nan)

fuel_encoded.fit(X_train[['fueltype']])
X_train['fuel_encoded'] = fuel_encoded.transform(X_train[['fueltype']]).ravel()
X_test['fuel_encoded'] = fuel_encoded.transform(X_test[['fueltype']]).ravel()

# Apply: One Hot Encoding on transmission type
transmission_ohe = OneHotEncoder(sparse_output = False, handle_unknown = 'ignore').set_output(transform = 'pandas')

transmission_ohe.fit(X_train[['drivewheel']])
encoded_df = transmission_ohe.transform(X_train[['drivewheel']])

encoded_test_df = transmission_ohe.transform(X_test[['drivewheel']])
# Concatenate encoded columns with original dataframe.
X_train = pd.concat([X_train, encoded_df], axis = 1)
X_test = pd.concat([X_test, encoded_test_df], axis = 1)

# Drop original categorical columns.
X_train = X_train.drop(columns = ['fueltype', 'drivewheel'])
X_test = X_test.drop(columns = ['fueltype', 'drivewheel'])

X_train

,car_ID,symboling,CarName,aspiration,doornumber,carbody,enginelocation,wheelbase,carlength,carwidth,...,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,fuel_encoded,drivewheel_4wd,drivewheel_fwd,drivewheel_rwd
66,67,0,mazda rx-7 gs,std,four,sedan,front,104.9,175.0,66.1,...,3.64,22.0,72,4200,31,39,NaN,0.0,0.0,1.0
111,112,0,peugeot 504,std,four,sedan,front,107.9,186.7,68.4,...,2.19,8.4,95,5000,19,24,NaN,0.0,0.0,1.0
153,154,0,toyota corona hardtop,std,four,wagon,front,95.7,169.7,63.6,...,3.03,9.0,62,4800,31,37,NaN,0.0,1.0,0.0
96,97,1,nissan latio,std,four,sedan,front,94.5,165.3,63.8,...,3.29,9.4,69,5200,31,37,NaN,0.0,1.0,0.0
38,39,0,honda civic 1300,std,two,hatchback,front,96.5,167.5,65.2,...,3.58,9.0,86,5800,27,33,NaN,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,107,1,nissan clipper,std,two,hatchback,front,99.2,178.5,67.9,...,3.27,9.0,160,5200,19,25,NaN,0.0,0.0,1.0
14,15,1,bmw z4,std,four,sedan,front,103.5,189.0,66.9,...,3.19,9.0,121,4250,20,25,NaN,0.0,0.0,1.0
92,93,1,nissan latio,std,four,sedan,front,94.5,165.3,63.8,...,3.29,9.4,69,5200,31,37,NaN,0.0,1.0,0.0
179,180,3,toyota corona,std,two,hatchback,front,102.9,183.5,67.7,...,3.35,9.3,161,5200,19,24,NaN,0.0,0.0,1.0
102,103,0,nissan fuga,std,four,wagon,front,100.4,184.6,66.5,...,3.27,9.0,152,5200,17,22,NaN,0.0,1.0,0.0

# Optional Problems

# 5. Heart Disease Dataset – Full Preprocessing Pipeline
Dataset Link:
Heart Disease UCI Dataset

Use the Heart Disease UCI Dataset dataset.

Tasks:

Build a preprocessing pipeline that includes:
- Missing value imputation
- Outlier detection using IQR
- One Hot Encoding
- Ordinal Encoding
- Use ColumnTransformer and Pipeline.
- Transform both training and testing datasets properly.
- Display final transformed feature matrix shape.

In [250]:
heart_dis_df = pd.read_csv('heart.csv')

# Missing value imputation
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# Outlier detection using IQR
numeric_cols = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']

for cols in numeric_cols:
    Q1 = heart_dis_df[cols].quantile(0.25)
    Q3 = heart_dis_df[cols].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    heart_dis_df = heart_dis_df[(heart_dis_df[cols] >= lower_bound) & (heart_dis_df[cols] <= upper_bound)]

print('Shape after IQR removal:', heart_dis_df.shape)

# Split FIRST
X = heart_dis_df.drop(['target'], axis=1)
y = heart_dis_df['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Impute on train only, transform both
imputer.fit(X_train)
X_train = pd.DataFrame(imputer.transform(X_train), columns=X_train.columns)
X_test  = pd.DataFrame(imputer.transform(X_test),  columns=X_test.columns)

# Use ColumnTransformer and Pipeline.
# one hot encoding
cp_ohe = Pipeline([('ohe', OneHotEncoder(sparse_output=False, handle_unknown='ignore').set_output(transform='pandas'))])

# Ordinal Encoding
thal_encod = Pipeline([('ord', OrdinalEncoder(categories=[[0, 1, 2, 3]], handle_unknown='use_encoded_value', unknown_value=np.nan))])

# ONE ColumnTransformer combining both
preprocessor = ColumnTransformer(transformers=[('cp_ohe', cp_ohe, ['cp']), ('thal_encod', thal_encod, ['thal'])], remainder='passthrough')

# Transform both training and testing datasets properly
X_train_transformed = preprocessor.fit_transform(X_train)
X_test_transformed  = preprocessor.transform(X_test)

# Display final transformed feature matrix shape
print('X_train transformed shape:', X_train_transformed.shape)
print('X_test  transformed shape:', X_test_transformed.shape)

Shape after IQR removal: (964, 14)
X_train transformed shape: (771, 16)
X_test  transformed shape: (193, 16)

# 6. Diabetes Dataset – Compare Encoding Techniques
Dataset Link:
Pima Indians Diabetes Dataset

Use the Pima Indians Diabetes Database dataset.

Tasks:

Create a categorical feature from BMI:
- Underweight
- Normal
- Overweight
- Obese

Apply:
- Label Encoding
- Ordinal Encoding
- One Hot Encoding

Write a short conclusion on which encoding is best for this feature.

In [251]:
diab_df = pd.read_csv('diabetes.csv')

# Create a categorical feature from BMI: 1. Underweight 2.Normal 3.Overweight 4.Obese
diab_df['BMI_State'] = pd.cut(diab_df['BMI'], bins = [0, 18.5, 24.9, 29.9, 100], labels = ['Underweight', 'Normal', 'Overweight', 'Obese'])

# Label Encoding
le_outcome = LabelEncoder()
le_outcome.fit(diab_df['BMI_State'])
diab_df['BMI_State_label_encoded'] = le_outcome.transform(diab_df['BMI_State'])

outcome_encoded = pd.Series(diab_df['BMI_State_label_encoded'], index = diab_df['BMI_State'], name = diab_df['BMI_State'].name)

# Ordinal Encoding
diab_ord = OrdinalEncoder(categories = [['Underweight', 'Normal', 'Overweight', 'Obese']], handle_unknown = 'use_encoded_value', unknown_value = np.nan)
diab_ord.fit(diab_df[['BMI_State']])
diab_df['BMI_State_encoded'] = diab_ord.transform(diab_df[['BMI_State']]).ravel()

# One Hot Encoding
bmi_ohe = OneHotEncoder(sparse_output = False).set_output(transform = 'pandas')

bmi_ohe.fit(diab_df[['BMI_State']])
bmi_encoded = bmi_ohe.transform(diab_df[['BMI_State']])

diab_df = pd.concat([diab_df, bmi_encoded], axis = 1)
diab_df


# Write a short conclusion on which encoding is best for this feature.
# Ordinal Encoding is the best for BMI_State because the categories have a clear natural order: Underweight < Normal < Overweight < Obese.
# Label Encoding also preserves order but assigns arbitrary integers without guaranteeing the correct sequence.
# One Hot Encoding is the worst choice here because it ignores the natural order and adds 4 extra columns unnecessarily.

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,BMI_State,BMI_State_label_encoded,BMI_State_encoded,BMI_State_Normal,BMI_State_Obese,BMI_State_Overweight,BMI_State_Underweight,BMI_State_nan
0,6,148,72,35,0,33.6,0.627,50,1,Obese,1,3.0,0.0,1.0,0.0,0.0,0.0
1,1,85,66,29,0,26.6,0.351,31,0,Overweight,2,2.0,0.0,0.0,1.0,0.0,0.0
2,8,183,64,0,0,23.3,0.672,32,1,Normal,0,1.0,1.0,0.0,0.0,0.0,0.0
3,1,89,66,23,94,28.1,0.167,21,0,Overweight,2,2.0,0.0,0.0,1.0,0.0,0.0
4,0,137,40,35,168,43.1,2.288,33,1,Obese,1,3.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0,Obese,1,3.0,0.0,1.0,0.0,0.0,0.0
764,2,122,70,27,0,36.8,0.340,27,0,Obese,1,3.0,0.0,1.0,0.0,0.0,0.0
765,5,121,72,23,112,26.2,0.245,30,0,Overweight,2,2.0,0.0,0.0,1.0,0.0,0.0
766,1,126,60,0,0,30.1,0.349,47,1,Obese,1,3.0,0.0,1.0,0.0,0.0,0.0
767,1,93,70,31,0,30.4,0.315,23,0,Obese,1,3.0,0.0,1.0,0.0,0.0,0.0

# 7. Hotel Booking Dataset – High Cardinality Encoding
Dataset Link:
Hotel Booking Demand Dataset

Use the Hotel Booking Demand Dataset dataset.

Tasks:
- Load dataset.
- Identify high-cardinality categorical columns.

Apply:
- One Hot Encoding on hotel
- Label Encoding on booking status column

In [252]:
# Load dataset.
hotel_df = pd.read_csv('hotel_bookings.csv')

# Identify high-cardinality categorical columns.
cat_cols = hotel_df.select_dtypes(include='object').columns
print('High-cardinality categorical columns: \n', hotel_df[cat_cols].nunique().sort_values(ascending=False))

# One Hot Encoding on hotel
hotel_ohe = OneHotEncoder(sparse_output = False, handle_unknown = 'ignore').set_output(transform = 'pandas')
hotel_ohe.fit(hotel_df[['hotel']])
hotel_encoded = hotel_ohe.transform(hotel_df[['hotel']])
hotel_df = pd.concat([hotel_df, hotel_encoded], axis = 1)

# Label Encoding on booking status column
le_booking = LabelEncoder()
le_booking.fit(hotel_df['reservation_status'])
hotel_df['reservation_status_encoded'] = le_booking.transform(hotel_df['reservation_status'])

hotel_df = hotel_df.drop(columns=['hotel'])
hotel_df

High-cardinality categorical columns:
 reservation_status_date    926
country                    177
assigned_room_type          12
arrival_date_month          12
reserved_room_type          10
market_segment               8
distribution_channel         5
meal                         5
customer_type                4
deposit_type                 3
reservation_status           3
hotel                        2
dtype: int64

,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,hotel_City Hotel,hotel_Resort Hotel,reservation_status_encoded
0,0,342,2015,July,27,1,0,0,2,0.0,...,0,Transient,0.00,0,0,Check-Out,2015-07-01,0.0,1.0,1
1,0,737,2015,July,27,1,0,0,2,0.0,...,0,Transient,0.00,0,0,Check-Out,2015-07-01,0.0,1.0,1
2,0,7,2015,July,27,1,0,1,1,0.0,...,0,Transient,75.00,0,0,Check-Out,2015-07-02,0.0,1.0,1
3,0,13,2015,July,27,1,0,1,1,0.0,...,0,Transient,75.00,0,0,Check-Out,2015-07-02,0.0,1.0,1
4,0,14,2015,July,27,1,0,2,2,0.0,...,0,Transient,98.00,0,1,Check-Out,2015-07-03,0.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,0,23,2017,August,35,30,2,5,2,0.0,...,0,Transient,96.14,0,0,Check-Out,2017-09-06,1.0,0.0,1
119386,0,102,2017,August,35,31,2,5,3,0.0,...,0,Transient,225.43,0,2,Check-Out,2017-09-07,1.0,0.0,1
119387,0,34,2017,August,35,31,2,5,2,0.0,...,0,Transient,157.71,0,4,Check-Out,2017-09-07,1.0,0.0,1
119388,0,109,2017,August,35,31,2,5,2,0.0,...,0,Transient,104.40,0,0,Check-Out,2017-09-07,1.0,0.0,1
119389,0,205,2017,August,35,29,2,7,2,0.0,...,0,Transient,151.20,0,2,Check-Out,2017-09-07,1.0,0.0,1

# 8. Employee Attrition Dataset – Advanced Encoding Challenge
Dataset Link:
IBM HR Analytics Employee Attrition Dataset

Use the IBM HR Analytics Employee Attrition Dataset dataset.

Tasks:
- Split the dataset into train and test sets.
- Detects all categorical columns automatically.

Apply:
- Ordinal Encoding for education level
- One Hot Encoding for department
- Label Encoding for target column
- Handle unseen categories in test data.
- Create a reusable preprocessing function.
- Display transformed train and test datasets.

In [253]:
hr_df = pd.read_csv('HR_Analytics.csv')

# Split the dataset into train and test sets.
X = hr_df.drop(['Attrition'], axis = 1)
y = hr_df['Attrition']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Detects all categorical columns automatically.
categ_cols = hr_df.select_dtypes(include='object').columns

# Ordinal Encoding for education level
X_train['Education_level'] = pd.cut(X_train['Education'], bins = [0, 1, 2, 3, 4, 5], labels = ['SSC', 'HSC', 'BBA', 'MBA', 'PHD'])
X_test['Education_level'] = pd.cut(X_test['Education'], bins = [0, 1, 2, 3, 4, 5], labels = ['SSC', 'HSC', 'BBA', 'MBA', 'PHD'])

edu_encode = OrdinalEncoder(categories = [['SSC', 'HSC', 'BBA', 'MBA', 'PHD']], handle_unknown = 'use_encoded_value', unknown_value = np.nan)
edu_encode.fit(X_train[['Education_level']])
X_train['Education_Encoded'] = edu_encode.transform(X_train[['Education_level']]).ravel()
X_test['Education_Encoded'] = edu_encode.transform(X_test[['Education_level']]).ravel()


# One Hot Encoding for department,
dept_ohe = OneHotEncoder(sparse_output=False, handle_unknown = 'ignore').set_output(transform = 'pandas')
dept_ohe.fit(X_train[['Department']])
dept_train_encode  = dept_ohe.transform(X_train[['Department']])
dept_test_encode  = dept_ohe.transform(X_test[['Department']])

X_train = pd.concat([X_train, dept_train_encode], axis = 1)
X_test = pd.concat([X_test, dept_test_encode], axis = 1)

# Label Encoding for target column
le_target = LabelEncoder()
le_target.fit(y_train)
y_train_array = le_target.transform(y_train)
y_test_array = le_target.transform(y_test)

y_train = pd.Series(y_train_array, index = y_train.index, name = y_train.name)
y_test = pd.Series(y_test_array, index = y_test.index, name = y_test.name)

# Create a reusable preprocessing function.
def preprocess(X_train, X_test, y_train, y_test):
  # Ordinal Encoding for education level
  X_train['Education_level'] = pd.cut(X_train['Education'], bins = [0, 1, 2, 3, 4, 5], labels = ['SSC', 'HSC', 'BBA', 'MBA', 'PHD'])
  X_test['Education_level'] = pd.cut(X_test['Education'], bins = [0, 1, 2, 3, 4, 5], labels = ['SSC', 'HSC', 'BBA', 'MBA', 'PHD'])

  edu_encode = OrdinalEncoder(categories = [['SSC', 'HSC', 'BBA', 'MBA', 'PHD']], handle_unknown = 'use_encoded_value', unknown_value = np.nan)
  edu_encode.fit(X_train[['Education_level']])
  X_train['Education_Encoded'] = edu_encode.transform(X_train[['Education_level']]).ravel()
  X_test['Education_Encoded'] = edu_encode.transform(X_test[['Education_level']]).ravel()

  # One Hot Encoding for department,
  dept_ohe = OneHotEncoder(sparse_output=False, handle_unknown = 'ignore').set_output(transform = 'pandas')
  dept_ohe.fit(X_train[['Department']])
  dept_train_encode  = dept_ohe.transform(X_train[['Department']])
  dept_test_encode  = dept_ohe.transform(X_test[['Department']])

  X_train = pd.concat([X_train, dept_train_encode], axis = 1)
  X_test = pd.concat([X_test, dept_test_encode], axis = 1)

  # Label Encoding for target column
  le_target = LabelEncoder()
  le_target.fit(y_train)
  y_train_array = le_target.transform(y_train)
  y_test_array = le_target.transform(y_test)

  y_train = pd.Series(y_train_array, index = y_train.index, name = y_train.name)
  y_test = pd.Series(y_test_array, index = y_test.index, name = y_test.name)

  return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = preprocess(X_train, X_test, y_train, y_test)

# Display transformed train and test datasets
print('X_train shape:', X_train.shape)
print('X_test  shape:', X_test.shape)
X_train

X_train shape: (1176, 42)
X_test  shape: (294, 42)

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,YearsSinceLastPromotion,YearsWithCurrManager,Education_level,Education_Encoded,Department_Human Resources,Department_Research & Development,Department_Sales,Department_Human Resources,Department_Research & Development,Department_Sales
1097,24,Travel_Rarely,350,Research & Development,21,2,Technical Degree,1,1551,3,...,0,0,HSC,1.0,0.0,1.0,0.0,0.0,1.0,0.0
727,18,Non-Travel,287,Research & Development,5,2,Life Sciences,1,1012,2,...,0,0,HSC,1.0,0.0,1.0,0.0,0.0,1.0,0.0
254,29,Travel_Rarely,1247,Sales,20,2,Marketing,1,349,4,...,0,2,HSC,1.0,0.0,0.0,1.0,0.0,0.0,1.0
1175,39,Travel_Rarely,492,Research & Development,12,3,Medical,1,1654,4,...,1,0,BBA,2.0,0.0,1.0,0.0,0.0,1.0,0.0
1341,31,Travel_Rarely,311,Research & Development,20,3,Life Sciences,1,1881,2,...,0,2,BBA,2.0,0.0,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1130,35,Travel_Rarely,750,Research & Development,28,3,Life Sciences,1,1596,2,...,6,8,BBA,2.0,0.0,1.0,0.0,0.0,1.0,0.0
1294,41,Travel_Rarely,447,Research & Development,5,3,Life Sciences,1,1814,2,...,1,2,BBA,2.0,0.0,1.0,0.0,0.0,1.0,0.0
860,22,Travel_Frequently,1256,Research & Development,3,4,Life Sciences,1,1203,3,...,0,0,MBA,3.0,0.0,1.0,0.0,0.0,1.0,0.0
1459,29,Travel_Rarely,1378,Research & Development,13,2,Other,1,2053,4,...,0,3,HSC,1.0,0.0,1.0,0.0,0.0,1.0,0.0
1126,50,Travel_Rarely,264,Sales,9,3,Marketing,1,1591,3,...,0,0,BBA,2.0,0.0,0.0,1.0,0.0,0.0,1.0