<a href="https://colab.research.google.com/github/Abrar-404/AI-ML_Practices_and_Assignments/blob/main/Module_14_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.kaggle.com/datasets/uciml/sms-spam-collection-dataset

In [80]:
import pandas as pd
import re
import string
from textblob import TextBlob
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize,sent_tokenize
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [45]:
# Problem 1
# Apply all the preprocessing techniques that you've leanred from the NLP Modules

df = pd.read_csv('/content/spam.csv', encoding = 'latin1', engine = 'python', on_bad_lines='skip')
df = df[['v1', 'v2']]
df.columns = ['label', 'message']

# lowercasing
df['message'] = df['message'].str.lower()

# remove html tag
def remove_html(text):
  pattern = re.compile('<.*?>')
  return pattern.sub(r'', text)

# remove url
def remove_url(text):
  pattern = re.compile(r"https?://\S+|www\.\S+")
  return pattern.sub(r'', text)

# remove punctuation
exclude = string.punctuation

def remove_punc(text):
  for char in exclude:
    text = text.replace(char, '')
  return text

# chat words
chat_words = {
    "A3": "Anytime, Anywhere, Anyplace",
    "ADIH": "Another Day In Hell",
    "AFK": "Away From Keyboard",
    "AFAIK": "As Far As I Know",
    "ASAP": "As Soon As Possible",
    "ATK": "At The Keyboard",
    "ATM": "At The Moment",
    "BAE": "Before Anyone Else",
    "BAK": "Back At Keyboard",
    "BBL": "Be Back Later",
    "BBS": "Be Back Soon",
    "BFN": "Bye For Now",
    "B4N": "Bye For Now",
    "BRB": "Be Right Back",
    "BRUH": "Bro",
    "BRT": "Be Right There",
    "BSAAW": "Big Smile And A Wink",
    "BTW": "By The Way",
    "BWL": "Bursting With Laughter",
    "CSL": "Can’t Stop Laughing",
    "CU": "See You",
    "CUL8R": "See You Later",
    "CYA": "See You",
    "DM": "Direct Message",
    "FAQ": "Frequently Asked Questions",
    "FC": "Fingers Crossed",
    "FIMH": "Forever In My Heart",
    "FOMO": "Fear Of Missing Out",
    "FR": "For Real",
    "FWIW": "For What It's Worth",
    "FYP": "For You Page",
    "FYI": "For Your Information",
    "G9": "Genius",
    "GAL": "Get A Life",
    "GG": "Good Game",
    "GMTA": "Great Minds Think Alike",
    "GN": "Good Night",
    "GOAT": "Greatest Of All Time",
    "GR8": "Great!",
    "HBD": "Happy Birthday",
    "IC": "I See",
    "ICQ": "I Seek You",
    "IDC": "I Don’t Care",
    "IDK": "I Don't Know",
    "IFYP": "I Feel Your Pain",
    "ILU": "I Love You",
    "ILY": "I Love You",
    "IMHO": "In My Honest/Humble Opinion",
    "IMU": "I Miss You",
    "IMO": "In My Opinion",
    "IOW": "In Other Words",
    "IRL": "In Real Life",
    "IYKYK": "If You Know, You Know",
    "JK": "Just Kidding",
    "KISS": "Keep It Simple, Stupid",
    "L": "Loss",
    "L8R": "Later",
    "LDR": "Long Distance Relationship",
    "LMK": "Let Me Know",
    "LMAO": "Laughing My A** Off",
    "LOL": "Laughing Out Loud",
    "LTNS": "Long Time No See",
    "M8": "Mate",
    "MFW": "My Face When",
    "MID": "Mediocre",
    "MRW": "My Reaction When",
    "MTE": "My Thoughts Exactly",
    "NVM": "Never Mind",
    "NRN": "No Reply Necessary",
    "NPC": "Non-Player Character",
    "OIC": "Oh I See",
    "OP": "Overpowered",
    "POV": "Point Of View",
    "PRT": "Party",
    "PRW": "Parents Are Watching",
    "ROFL": "Rolling On The Floor Laughing",
    "ROFLOL": "Rolling On The Floor Laughing Out Loud",
    "ROTFLMAO": "Rolling On The Floor Laughing My A** Off",
    "RN": "Right Now",
    "SK8": "Skate",
    "SUS": "Suspicious",
    "TBH": "To Be Honest",
    "TFW": "That Feeling When",
    "THX": "Thank You",
    "TIME": "Tears In My Eyes",
    "TLDR": "Too Long, Didn’t Read",
    "TNTL": "Trying Not To Laugh",
    "TTFN": "Ta-Ta For Now!",
    "TTYL": "Talk To You Later",
    "U": "You",
    "U2": "You Too",
    "U4E": "Yours For Ever",
    "W": "Win",
    "W8": "Wait...",
    "WB": "Welcome Back",
    "WTG": "Way To Go!",
    "WUF": "Where Are You From?",
    "WYD": "What You Doing?",
    "WYWH": "Wish You Were Here",
    "ZZZ": "Sleeping, Bored, Tired",
    "OMG!": "Oh My God",
    "SMH": "Shaking My Head",
    "NGL": "Not Gonna Lie",
    "TBF": "To Be Fair",
    "ICYMI": "In Case You Missed It",
    "IMO": "In My Opinion",
    "IMHO": "In My Honest Opinion",
    "RN": "Right Now",
    "FR": "For Real",
    "DW": "Don't Worry",
    "ILYSM": "I Love You So Much",
    "OMW": "On My Way",
    "GGWP": "Good Game Well Played",
    "GG": "Good Game",
    "EZ": "Easy",
    "LMAO": "Laughing My A** Off",
    "LOL": "Laughing Out Loud"
}

def chat_conversion(text):
  new_text = []

  for w in text.split():
    if w.upper() in chat_words:
      new_text.append(chat_words[w.upper()])
    else:
      new_text.append(w)
  return ' '.join(new_text)

# spell checking
# df['message'] = df['message'].apply(lambda x: TextBlob(x).correct().string)
# df['message']

# stop words
stop_words = stopwords.words('english')

def remove_stopwords(text):
  words = text.split()
  cleaned = []

  for word in words:
    word = word.lower().strip(string.punctuation)

    if word and word not in stop_words:
      cleaned.append(word)
  return ' '.join(cleaned)

# emoji removal
def remove_emoji(text):
  emoji_pattern = re.compile(
      "["
        "\U0001F600-\U0001F64F"  # emoticons
        "\U0001F300-\U0001F5FF"  # symbols & pictographs
        "\U0001F680-\U0001F6FF"  # transport & map symbols
        "\U0001F1E0-\U0001F1FF"  # flags
        "\U00002700-\U000027BF"  # dingbats
        "\U000024C2-\U0001F251"
        "]+",
        flags=re.UNICODE
  )
  return emoji_pattern.sub(r'', text)

# apply all the funcs
df['message'] = df['message'].apply(remove_html)
df['message'] = df['message'].apply(remove_url)
df['message'] = df['message'].apply(remove_punc)
df['message'] = df['message'].apply(chat_conversion)
df['message'] = df['message'].apply(remove_stopwords)
df['message'] = df['message'].apply(remove_emoji)

# tokenize
df['tokens'] = df['message'].apply(word_tokenize)

# stemming
ps = PorterStemmer()

def stem_words(text):
  return ' '.join([ps.stem(word) for word in text.split()])

df['stemmed'] = df['message'].apply(stem_words)

# lemmatization
wordnet_lemmatizer = WordNetLemmatizer()
def lemmatize_words(text):
  return ' '.join([wordnet_lemmatizer.lemmatize(word, pos = 'v') for word in word_tokenize(text) ])

df['lemmatized'] = df['message'].apply(lemmatize_words)

In [46]:
# Problem 2
# Find out the number of words in the entire corpus and also the total number of unique words(vocabulary) using just python

words = []

for text in df['message']:
  words.extend(text.split())

print('Total Words:', len(words))
print("Vocabulary size:", len(set(words)))

Total Words: 51500
Vocabulary size: 9337

In [58]:
# Problem 3
# Apply One Hot Encoding
words_df = pd.DataFrame({'word': words})
encoder = OneHotEncoder(sparse_output=True, handle_unknown = 'ignore')
words_matrix = encoder.fit_transform(words_df)
print(words_matrix.shape)

(51500, 9337)

In [70]:
# Problem 4

# Apply bag words and find the vocabulary also find the times each word has occured

# bag of words
cv = CountVectorizer(binary = True)
bow = cv.fit_transform(df['message'])

# size of vocabulary
vocab = cv.get_feature_names_out()
vocab_size = len(vocab)
print('Vocabulary size:', vocab_size)

# how many times each word occured
counts = bow.sum(axis = 0).A1
word_counts = pd.DataFrame({'words': vocab, 'counts': counts})
word_counts.sort_values('counts', ascending = False).head(20)

Vocabulary size: 9284

      words  counts
1919   call     535
4306     im     422
3700    get     370
8600     ur     306
5908     ok     270
3748     go     260
2892   dont     248
4741   know     246
4303    ill     231
3805    got     227
4927   like     226
3544   free     225
3781   good     222
5090   ltgt     214
2287   come     212
3265   eyes     206
8063  tears     198
2612    day     189
7187   send     186
8807   want     185

In [79]:
# Problem 5

# Apply bag of bi-gram and bag of tri-gram and write down your observation about the dimensionality of the vocabulary

# Unigram (for comparison)
uni = CountVectorizer()
uni_matrix = uni.fit_transform(df['message'])

# Bigram
bi = CountVectorizer(ngram_range=(2, 2))
bi_matrix = bi.fit_transform(df['message'])

# Trigram
tri = CountVectorizer(ngram_range=(3, 3))
tri_matrix = tri.fit_transform(df['message'])

print("Unigram vocabulary:", uni_matrix.shape[1])
print("Bigram vocabulary: ", bi_matrix.shape[1])
print("Trigram vocabulary:", tri_matrix.shape[1])

print()

# Look at a few examples
print(bi.get_feature_names_out()[:10])
print(tri.get_feature_names_out()[:10])

# My observation
# With single words, I found 9,284 different words. When I counted pairs of words (bigrams), the number jumped to 31,770. That’s more than three times bigger,
# because there are many more ways to pair up words than there are single words.

# Triples of words (trigrams) came out at 31,732, almost the same as pairs. I expected it to keep growing,
# but it didn’t. The messages are short, because I removed small words like “the” and “is”.
# A short message has fewer triples than pairs, and a very short one has no triples at all.

# Most pairs and triples show up only once. So the table is mostly zeros and gets really huge. That means more memory and slower work for the computer.
# The good part is that pairs and triples keep a bit of context. For example, “not good” means something different from “good” alone, and single words can’t show that.

Unigram vocabulary: 9284
Bigram vocabulary:  31770
Trigram vocabulary: 31732

['008704050406 sp' '0089my last' '0121 2025050' '01223585236 xx'
 '01223585334 cum' '0125698789 ring' '02 user' '020603 2nd' '0207 153'
 '02072069400 bx']
['008704050406 sp arrow' '0089my last four' '0121 2025050 visit'
 '01223585236 xx luv' '01223585334 cum wan' '0125698789 ring ur'
 '02 user today' '020603 2nd attempt' '0207 153 9153' '0207 153 9996']

In [89]:
# Problem 6

# Apply tf-idf and find out the idf scores of words
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(df['message'])

columns = tfidf.get_feature_names_out()

idf_df = pd.DataFrame({
    'words': columns,
    'idf_scores': tfidf.idf_
})

print('Vocabulary Size:', len(idf_df))
idf_df.sort_values('idf_scores', ascending = False).head(20)

Vocabulary Size: 9284

            words  idf_scores
9283       ûówell    8.932542
9281      ûïharry    8.932542
9265         zouk    8.932542
9264         zoom    8.932542
9263    zogtorius    8.932542
9261       zindgi    8.932542
9260        zhong    8.932542
9259        zeros    8.932542
9257        zebra    8.932542
9256      zealand    8.932542
9255       zahers    8.932542
9254          zac    8.932542
9253       ywhere    8.932542
9252         yupz    8.932542
9250         yuou    8.932542
31    07753741225    8.932542
28    07732584351    8.932542
27        0721072    8.932542
24    07099833605    8.932542
23    07090298926    8.932542