<a href="https://colab.research.google.com/github/Abrar-404/AI-ML_Practices_and_Assignments/blob/main/Module_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Version 1

In [16]:
import torch
import torch.nn as nn

In [17]:
# class Model(nn.Module):
#   def __init__(self, num_features):
#     super().__init__()

#     self.linear = nn.Linear(num_features, 1)
#     self.sigmoid = nn.Sigmoid()

#   def forward(self, features):
#     out = self.linear(features)
#     out  = self.sigmoid(out)
#     return out

In [18]:
# Create Dataset

In [19]:
# features = torch.rand(10, 5)
# features

tensor([[0.7323, 0.6574, 0.3867, 0.0795, 0.0957],
        [0.6758, 0.9570, 0.5984, 0.5158, 0.2550],
        [0.5144, 0.4766, 0.0235, 0.6406, 0.9096],
        [0.2918, 0.3451, 0.8875, 0.3678, 0.2745],
        [0.5802, 0.2606, 0.9827, 0.6298, 0.5315],
        [0.1725, 0.8190, 0.6561, 0.0604, 0.7663],
        [0.0213, 0.2437, 0.5225, 0.9470, 0.2560],
        [0.2503, 0.5641, 0.6245, 0.6299, 0.5020],
        [0.8510, 0.8153, 0.1240, 0.0845, 0.6246],
        [0.7199, 0.2894, 0.8721, 0.5610, 0.4817]])

In [20]:
# features.shape[1]

5

In [21]:
# # create model

# model = Model(features.shape[1])

In [22]:
# # calling model for forward pass

# model(features)

tensor([[0.5214],
        [0.4436],
        [0.4161],
        [0.4867],
        [0.4918],
        [0.4180],
        [0.4119],
        [0.4182],
        [0.4808],
        [0.5092]], grad_fn=<SigmoidBackward0>)

In [29]:
# # show model weights

# model.linear.weight

Parameter containing:
tensor([[ 0.4203, -0.4216,  0.1048, -0.3417, -0.2206]], requires_grad=True)

In [24]:
# visualize

!pip install torchinfo

Requirement already satisfied: torchinfo in /usr/local/lib/python3.12/dist-packages (1.8.0)

In [25]:
# from torchinfo import summary

# summary(model, input_size = (10, 5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
==========================================================================================
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

# Version 2

In [26]:
# class Model(nn.Module):
#   def __init__(self, num_features):
#     super().__init__()

#     # layer 1
#     self.linear1 = nn.Linear(num_features, 3)
#     self.relu = nn.ReLU()

#     # layer2
#     self.linear2 = nn.Linear(3, 1)
#     self.sigmoid = nn.Sigmoid()

#   def forward(self, features):
#     out = self.linear1(features)
#     out = self.relu(out)

#     out = self.linear2(out)
#     out  = self.sigmoid(out)

#     return out

# Version 3

In [38]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()

    self.network = nn.Sequential(
        nn.Linear(num_features, 3),             # index 0
        nn.ReLU(),                              # index 1
        nn.Linear(3, 1),                        # index 2
        nn.Sigmoid()                            # index 3
    )


  def forward(self, features):
    out = self.network(features)

    return out

In [32]:
# Create dataset

features = torch.rand(10,5)
features

tensor([[0.9501, 0.0437, 0.3768, 0.1143, 0.9130],
        [0.0583, 0.9216, 0.7868, 0.9888, 0.8852],
        [0.1183, 0.0247, 0.9503, 0.3428, 0.4106],
        [0.7462, 0.7744, 0.5560, 0.0179, 0.6369],
        [0.4060, 0.1811, 0.9485, 0.0577, 0.9778],
        [0.2704, 0.6293, 0.5328, 0.2225, 0.9457],
        [0.3456, 0.6916, 0.9576, 0.7549, 0.0063],
        [0.6527, 0.8966, 0.6744, 0.9445, 0.8414],
        [0.7663, 0.4354, 0.8458, 0.2106, 0.5007],
        [0.9990, 0.1345, 0.5441, 0.9389, 0.4553]])

In [33]:
features.shape[1]

5

In [34]:
#create model

model = Model(features.shape[1])

In [35]:
#calling model for forward pass
# model.forward(features)

model(features)

tensor([[0.5582],
        [0.5049],
        [0.5147],
        [0.5582],
        [0.5381],
        [0.5267],
        [0.5201],
        [0.5282],
        [0.5510],
        [0.5366]], grad_fn=<SigmoidBackward0>)

In [41]:
model.network[2].weight

Parameter containing:
tensor([[0.1532, 0.1724, 0.3570]], requires_grad=True)

In [36]:
# visualize

!pip install torchinfo

Requirement already satisfied: torchinfo in /usr/local/lib/python3.12/dist-packages (1.8.0)

In [37]:
from torchinfo import summary

summary( model,input_size = (10,5) )

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
==========================================================================================
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

# Import Libraries

In [42]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [50]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [45]:
df.shape

(569, 31)

In [51]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [48]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# Train test split

In [49]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [52]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [53]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [54]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [55]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [56]:
len(df.columns)

31

In [57]:
X_train

array([[-0.52453407, -0.07462481, -0.58481581, ..., -1.13197854,
        -0.6017003 , -0.66950624],
       [ 0.05122807, -1.36552975,  0.0128711 , ..., -0.09394403,
         0.25668847, -1.31758572],
       [ 1.78133685,  0.30915774,  1.73648086, ...,  0.69886293,
         0.52366766, -1.13829325],
       ...,
       [-0.70516533, -0.52818601, -0.7555835 , ..., -1.08992661,
        -0.30261602, -0.88762638],
       [-1.67634059,  0.3161356 , -1.59022079, ..., -0.54475878,
         0.69602131,  3.70031959],
       [ 1.2140418 , -0.19092255,  1.18087307, ...,  0.74257282,
         1.32629495,  0.1138991 ]])

In [58]:
y_train

array([0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1])

In [60]:
type(y_train)

numpy.ndarray

In [61]:
type(y_test)

numpy.ndarray

# Numpy Array to tensors

In [62]:
#numpy to tensor
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

#change dtype
X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)

#numpy to tensor
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

# y_test_tensor = torch.from_numpy(y_test)

/tmp/ipykernel_533/3826779354.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
/tmp/ipykernel_533/3826779354.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)
/tmp/ipykernel_533/3826779354.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
/tmp/ipykernel_533/3826779354.py:14: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

In [63]:
type(X_train_tensor)

torch.Tensor

# Defining the Model

In [64]:
X_train.shape[1]

30

In [65]:
import torch.nn as nn

In [66]:
class MySimpleNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [67]:
torch.rand(30,1)

tensor([[0.6980],
        [0.4599],
        [0.4507],
        [0.8181],
        [0.3489],
        [0.6943],
        [0.2503],
        [0.8018],
        [0.5977],
        [0.4235],
        [0.7002],
        [0.5494],
        [0.6811],
        [0.2714],
        [0.3913],
        [0.7613],
        [0.2161],
        [0.0595],
        [0.9223],
        [0.7304],
        [0.4293],
        [0.9096],
        [0.4922],
        [0.7767],
        [0.3040],
        [0.1456],
        [0.4728],
        [0.3189],
        [0.4269],
        [0.4503]])

In [68]:
X_train_tensor.shape[1]

30

In [69]:
learning_rate = 0.1
epochs = 25

In [70]:
loss_function = nn.BCELoss()

In [71]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [72]:
model = MySimpleNN(X_train_tensor.shape[1])

In [73]:
model.parameters()

In [74]:
X_test_tensor.dtype

torch.float32

In [75]:
model.linear.weight.dtype

torch.float32

In [76]:
y_train_tensor.dtype

torch.float32

In [77]:
model.parameters()

# Training Pipeline

In [ ]:
#create model

model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop

for epoch in range(epochs):

  #forward pass
  y_pred = model(X_train_tensor)


  #Loss calculate
  loss = loss_function(y_pred,y_train_tensor.reshape(-1,1))

   #zero gradient
  optimizer.zero_grad()


  #backward pass
  loss.backward()


  #parameter update
  optimizer.step()



  #print loss in each epoch

  print(f" {epoch+1} , Loss = {loss.item()} ")

# Model Evaluation

In [78]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred= (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f" Accuracy = {accuracy.item()}")

 Accuracy = 0.640350878238678

# Summary

In [79]:
X_train_tensor.shape

torch.Size([455, 30])

In [80]:
!pip install torchinfo

Requirement already satisfied: torchinfo in /usr/local/lib/python3.12/dist-packages (1.8.0)

In [81]:
from torchinfo import summary

In [82]:
summary(model, input_size = (455,30))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
MySimpleNN                               [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
==========================================================================================
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
==========================================================================================
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06
==========================================================================================